# Generated by Django 5.0.4 on 2026-04-04 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('icon', models.CharField(default='bi-device-hdd', max_length=50, verbose_name='Ícone Bootstrap')),
            ],
            options={
                'verbose_name': 'Categoria de Ativo',
                'verbose_name_plural': 'Categorias de Ativos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome / Identificação')),
                ('asset_type', models.CharField(choices=[('laptop', 'Notebook'), ('desktop', 'Desktop'), ('server', 'Servidor'), ('printer', 'Impressora'), ('network', 'Equipamento de Rede'), ('monitor', 'Monitor'), ('phone', 'Telefone / VOIP'), ('mobile', 'Smartphone / Tablet'), ('other', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model_name', models.CharField(max_length=200, verbose_name='Modelo')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Número de Série')),
                ('asset_tag', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Patrimônio')),
                ('status', models.CharField(choices=[('active', 'Em Uso'), ('available', 'Disponível'), ('maintenance', 'Em Manutenção'), ('inactive', 'Inativo'), ('disposed', 'Descartado')], default='available', max_length=20, verbose_name='Status')),
                ('condition', models.CharField(choices=[('new', 'Novo'), ('good', 'Bom'), ('fair', 'Regular'), ('poor', 'Ruim')], default='good', max_length=20, verbose_name='Estado')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Localização')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Data de Compra')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='Garantia até')),
                ('purchase_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de Compra (R$)')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Fornecedor')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='Endereço MAC')),
                ('operating_system', models.CharField(blank=True, max_length=100, verbose_name='Sistema Operacional')),
                ('processor', models.CharField(blank=True, max_length=200, verbose_name='Processador')),
                ('ram', models.CharField(blank=True, max_length=50, verbose_name='Memória RAM')),
                ('storage', models.CharField(blank=True, max_length=100, verbose_name='Armazenamento')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Ativo de TI',
                'verbose_name_plural': 'Ativos de TI',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventiva'), ('corrective', 'Corretiva'), ('upgrade', 'Upgrade'), ('cleaning', 'Limpeza')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('in_progress', 'Em Andamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='scheduled', max_length=20, verbose_name='Status')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('performed_by', models.CharField(blank=True, max_length=200, verbose_name='Realizado por')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Data Agendada')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo (R$)')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='assets.asset', verbose_name='Ativo')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
            ],
            options={
                'verbose_name': 'Registro de Manutenção',
                'verbose_name_plural': 'Registros de Manutenção',
                'ordering': ['-created_at'],
            },
        ),
    ]
