# Generated by Django 6.0.3 on 2026-04-04 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('ERP_PROTHEUS', 'ERP Protheus'), ('OFFICE_EXCEL', 'Excel / Office'), ('OFFICE_WORD', 'Word / Office'), ('DATABASE', 'Banco de Dados'), ('WEBSITE', 'Website / Intranet'), ('API', 'API / Integração'), ('NETWORK', 'Rede / Conectividade'), ('ACCESS', 'Acesso / Permissões'), ('HARDWARE', 'Hardware'), ('PRINTER', 'Impressora / Periférico'), ('EMAIL', 'E-mail'), ('BACKUP', 'Backup / Storage'), ('UNKNOWN', 'Não Identificado')], max_length=30, verbose_name='Domínio')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Sintoma')),
                ('keywords', models.TextField(help_text='Separe por vírgula. Ex: lento,travando,timeout,queda', verbose_name='Palavras-chave')),
                ('probable_cause', models.TextField(verbose_name='Causa Provável')),
                ('checklist', models.TextField(help_text='Uma ação por linha', verbose_name='Checklist Técnico')),
                ('recommended_action', models.TextField(verbose_name='Ação Recomendada')),
                ('priority_hint', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='Sugestão de Prioridade')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entrada do Playbook',
                'verbose_name_plural': 'Playbook — Base de Conhecimento',
                'ordering': ['domain', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RecurrenceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('asset', 'Ativo / Equipamento'), ('department', 'Setor / Departamento'), ('category', 'Categoria'), ('domain', 'Domínio Técnico')], max_length=20, verbose_name='Escopo')),
                ('scope_value', models.CharField(max_length=200, verbose_name='Valor do Escopo')),
                ('domain', models.CharField(blank=True, choices=[('ERP_PROTHEUS', 'ERP Protheus'), ('OFFICE_EXCEL', 'Excel / Office'), ('OFFICE_WORD', 'Word / Office'), ('DATABASE', 'Banco de Dados'), ('WEBSITE', 'Website / Intranet'), ('API', 'API / Integração'), ('NETWORK', 'Rede / Conectividade'), ('ACCESS', 'Acesso / Permissões'), ('HARDWARE', 'Hardware'), ('PRINTER', 'Impressora / Periférico'), ('EMAIL', 'E-mail'), ('BACKUP', 'Backup / Storage'), ('UNKNOWN', 'Não Identificado')], max_length=30, verbose_name='Domínio')),
                ('level', models.CharField(choices=[('light', 'Leve'), ('medium', 'Moderado'), ('critical', 'Crítico')], max_length=20, verbose_name='Nível')),
                ('occurrences', models.IntegerField(verbose_name='Ocorrências')),
                ('period_days', models.IntegerField(verbose_name='Período (dias)')),
                ('first_seen', models.DateTimeField(verbose_name='Primeiro Chamado')),
                ('last_seen', models.DateTimeField(verbose_name='Último Chamado')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resolvido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerta de Reincidência',
                'verbose_name_plural': 'Alertas de Reincidência',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_detected', models.CharField(choices=[('ERP_PROTHEUS', 'ERP Protheus'), ('OFFICE_EXCEL', 'Excel / Office'), ('OFFICE_WORD', 'Word / Office'), ('DATABASE', 'Banco de Dados'), ('WEBSITE', 'Website / Intranet'), ('API', 'API / Integração'), ('NETWORK', 'Rede / Conectividade'), ('ACCESS', 'Acesso / Permissões'), ('HARDWARE', 'Hardware'), ('PRINTER', 'Impressora / Periférico'), ('EMAIL', 'E-mail'), ('BACKUP', 'Backup / Storage'), ('UNKNOWN', 'Não Identificado')], default='UNKNOWN', max_length=30, verbose_name='Domínio Detectado')),
                ('domain_confidence_score', models.IntegerField(default=0, verbose_name='Score de Domínio (0-100)')),
                ('similar_tickets_count', models.IntegerField(default=0, verbose_name='Chamados Similares Encontrados')),
                ('similar_tickets_ids', models.TextField(blank=True, default='', verbose_name='IDs dos Similares')),
                ('recurrence_level', models.CharField(blank=True, choices=[('light', 'Leve'), ('medium', 'Moderado'), ('critical', 'Crítico')], max_length=20, null=True, verbose_name='Nível de Reincidência')),
                ('recurrence_count_7d', models.IntegerField(default=0, verbose_name='Ocorrências (7 dias)')),
                ('recurrence_count_15d', models.IntegerField(default=0, verbose_name='Ocorrências (15 dias)')),
                ('recurrence_count_30d', models.IntegerField(default=0, verbose_name='Ocorrências (30 dias)')),
                ('confidence', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='low', max_length=10, verbose_name='Confiança Geral')),
                ('confidence_percent', models.IntegerField(default=0, verbose_name='Confiança (%)')),
                ('generated_at', models.DateTimeField(auto_now=True, verbose_name='Gerado em')),
                ('notes', models.TextField(blank=True, verbose_name='Observações do Motor')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic', to='tickets.ticket', verbose_name='Chamado')),
                ('playbook_matched', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostics.playbookentry', verbose_name='Playbook Aplicado')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos Gerados',
            },
        ),
    ]
